package com.example.fintechapp.common

object AppLanguage {
    const val DTGENTA = "DTGenta"
    const val CONVENIENT_PERSONAL_LOANS: String = "Convenient Personal Loans"
    const val EASY_PAYMENT_ONLINE: String = "Easy Payment Online"
    const val WHERE_YOU_ARE_EMPLOYED: String =
        "Whether you’re employed or run your own business, our loans of up to ₦200,000 can help you meet your needs conveniently"
    const val MAKE_YOUR_PAYMENT: String =
        "Make your payment experience more better today. No additional admin fee"
    const val REGISTER_NOW: String = "Register Now"
    const val ALREADY_HAVE_AN_ACCOUNT: String = "Already Have An Account"
    const val WELCOME_TO_DTGENTA = "Welcome to DtGenta!"
    const val JOIN_US_CREATE_ACCOUNT_YOUR_TODAY = "Join us, create your account today"
    const val CONTINUE = "Continue"
    const val EMAIL = "Email"
    const val ENTER_EMAIL = "Enter Email"
    const val ENTER_PHONE_NUMBER = "Enter Phone Number"
    const val PASSWORD = "Password"
    const val ENTER_PASSWORD = "Enter Password"
    const val CONFIRM_PASSWORD = "Confirm Password"
    const val ENTER_CONFIRM_PASSWORD = "Enter confirm Password"
    const val FIELD_CANNOT_BE_EMPTY_ERROR = "Field cannot be empty"
    const val OR = "OR"
    const val LOGIN = "Login"
    const val PLEASE_ENTER_A_VALID_EMAIL_ADDRESS = "Please enter a valid email address"
    const val PASSWORD_MINIMUM_EIGHT_CHARACTERS = "Password minimum 8 characters"
    const val PHONE_NUMBER_MUST_HAVE_AT_LEAST_TEN_DIGIT =
        "Phone number must have at least 10 digits."
    const val DOES_NOT_MATCH_THE_PASSWORD = "Does not match the password"
    const val PERSONAL_DETAILS = "Personal Details"
    const val ENTER_YOUR_DETAILS = "Enter your details as they appear on your legal documents"
    const val FIRST_NAME = "First Name"
    const val LAST_NAME = "Last Name"
    const val DATE_OF_BIRTH = "Date of birth"
    const val DD_MM_YY = "DD/MM/YY"
    const val CREATE_ACCOUNT = "Create account"
    const val PLEASE_SIGN_IN_TO_YOUR_ACCOUNT =
        "Please sign-in to your account to unlock all features"
    const val DO_NOT_HAVE_ACCOUNT = "Don’t have an account?"
    const val SIGN_UP = "Sign Up"
    const val PHONE_NUMBER = "Phone Number"
    const val REMEMBER_ME = "Remember me"
    const val CONFIRM = " Confirm"
    const val INCORRECT_PHONE_NUMBER_OR_PASSWORD = "Incorrect phone number or password"
    const val SOMETHING_WENT_WRONG = "Something went wrong"
    const val FAILED = " Failed"
    const val AGENT_LIST = "Agent list"
    const val SEARCH = "Search..."
    const val NEW_AGENT = "New agent"
    const val AGENT = "Agent"
    const val QR_CODE_PRODUCTS = "QR code products"
    const val GIFT = "Gift"
    const val WINNING_CODE = "Winning code"
    const val CLIENT = "Client"
    const val PROGRAMME = "Programme"
    const val NOTIFICATION = "Notification"
    const val ADVERTISEMENT = "advertisement"
    const val LUCKY_SPIN = "Lucky spin"
    const val SETTING = "Setting"
    const val PROFILE = "Profile"
    const val LOGOUT = "Logout"
    const val AGENT_NAME = "AGENT NAME"
    const val AGENT_CODE = "AGENT CODE"
    const val CITY = "CITY"
    const val FARMERS_COUNT = "FARMERS COUNT"
    const val DETAILS = "Detail"
    const val UPDATE = "Update"
    const val REMOVE = "Remove"
    const val CANCEL = "Cancel"
    const val DELETE_AGENCY = "Delete Agency"
    const val ARE_YOU_SURE_YOU_WANT_TO_DELETE_THIS_AGENCY =
        "Are you sure you want to delete this agent?"
}